### PR TITLE
Buttons

### PR DESCRIPTION
**Pull request by DavidMatalik**
These code changes do

1. Render an edit and a submit button in each component
2. Restructure code so that a form is integrated for handling input fields and button clicks
3. Control input values with react
4. Render divs with input values after click on submit button
5. Render input fields with values of divs after click on edit button

Can you please review especially: 

1. It appears to me to be a lot of code in CVSectionForm.js. I tried first put input fields into extra component. But then you aren't really able to control their values with React state, are you?
2. Would you say the code division in the different components makes sense in general? 

buttonsPR

### CODE REVIEW

**Comment by RichStone** [comment]
The first part of your PR description:

> These code changes do
> ...

is a bit redundant, because the what is already shown here:
image
(and in the commit messages)

Better focus on the Why in the description and the purpose of the PR.

It's great that you came up with specific questions! I usually put them in a separate comment (because the "PR description" is there to describe the PR ;) )

**Comment by RichStone** [comment]
> It appears to me to be a lot of code in CVSectionForm.js. I tried first put input fields into extra component. But then you aren't really able to control their values with React state, are you?

I think you can pass values as props from your Form component and then "control" them inside the input component, but I think it'd best to play it out in a scenario together or if you give a specific example :)

**Comment by RichStone** [comment]
> Would you say the code division in the different components makes sense in general?

it smells a bit after duplication, since the only different thing is the function that's used. I guess here again, we could pass some props to the component. It's probably good to have the button component though! And then make it dynamic. 

And the Form is something that seems like a candidate for a container if you remember our discussion from last time, but that's just a side note.

**Comment by RichStone** [comment]
I think you handled this exercise well but could try to recreate the input components and move the logic inside of them :thinking: 

And you could try to remove the duplication of the 2 button components, you can achieve the same with just one component

**Comment by RichStone** [comment]
feel free to decide if you want to give it a shot or if you want to practice this kind of stuff in the next React projects

**Comment by DavidMatalik** [comment]
> Better focus on the Why in the description and the purpose of the PR.

Ok I will do so in future, thank you for the feedback.

**Comment by DavidMatalik** [comment]
> it smells a bit after duplication, since the only different thing is the function that's used. I guess here again, we could pass some props to the component. It's probably good to have the button component though! And then make it dynamic.
 
So you would write e.g. CVSectionHeading not as extra component, but rather put it inside the component CVSection?

**Comment by DavidMatalik** [comment]
> I think you can pass values as props from your Form component and then "control" them inside the input component, but I think it'd best to play it out in a scenario together or if you give a specific example :)

Yes you are right. :) I fiddled around [with the form example from offical React docs about controlled components](https://reactjs.org/docs/forms.html#controlled-components). And it worked with making the input field an extra component passing down `this.state.value` and `this.handleChange` as props. So I am also going to change it in here.

**Comment by DavidMatalik** [comment]
> And you could try to remove the duplication of the 2 button components, you can achieve the same with just one component

Ah now I understand what you meant with duplication. Ok I am going to change this as well.

**Comment by RichStone** [comment]
Thanks for the changes, cool solution!

**Pull request merged**
